name: Build Godot Android APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  export:
    name: Export Android APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Export APK with crystal-bit/godot-export
        uses: crystal-bit/godot-export@v3
        with:
          godot-version: 4.2.2 # Ganti sesuai versi Godot project kamu
          export-template-version: 4.2.2
          preset: "Android"
          output: "build/android/gamefer.apk"

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gamefer-android-apk
          path: build/android/gamefer.apk
