name: "Build Android"

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

env:
  GODOT_VERSION: 4.2.2
  EXPORT_NAME: gamefer

jobs:
  # Approach Docker dengan versi yang tersedia
  export-android-docker:
    name: Android Export (Docker)
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.2.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Export Templates
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

      - name: Create Export Presets
        run: |
          cat > export_presets.cfg << 'EOF'
          [preset.0]
          
          name="Android"
          platform="Android"
          runnable=true
          dedicated_server=false
          custom_features=""
          export_filter="all_resources"
          include_filter=""
          exclude_filter=""
          export_path=""
          encryption_include_filters=""
          encryption_exclude_filters=""
          encrypt_pck=false
          encrypt_directory=false
          
          [preset.0.options]
          
          custom_template/debug=""
          custom_template/release=""
          gradle_build/use_gradle_build=false
          gradle_build/export_format=0
          gradle_build/min_sdk=""
          gradle_build/target_sdk=""
          architectures/armeabi-v7a=false
          architectures/arm64-v8a=true
          architectures/x86=false
          architectures/x86_64=false
          version/code=1
          version/name="1.0"
          package/unique_name="com.gamefer.app"
          package/name="GameFer"
          package/signed=false
          permissions/internet=false
          EOF

      - name: Import Project (Fix Resource Issues)
        run: |
          echo "Importing project to fix resource UIDs..."
          godot --headless --editor --quit-after 30 || true
          
      - name: Build Android APK
        run: |
          mkdir -v -p build/android
          echo "Starting Android export..."
          godot --headless --verbose --export-debug "Android" build/android/$EXPORT_NAME.apk
          
          echo "=== Export Results ==="
          ls -la build/android/
          if [ -f "build/android/$EXPORT_NAME.apk" ]; then
            echo "✅ APK created successfully!"
            file build/android/$EXPORT_NAME.apk
          else
            echo "❌ APK not found"
            find . -name "*.apk" 2>/dev/null || echo "No APK files found anywhere"
          fi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: android-${{ env.EXPORT_NAME }}-docker
          path: build/android/
          retention-days: 14

  # Manual approach dengan resource fix
  export-android-manual:
    name: Android Export (Manual - Fixed)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Godot
        run: |
          wget -q https://github.com/godotengine/godot/releases/download/4.2.2-stable/Godot_v4.2.2-stable_linux.x86_64.zip
          unzip -q Godot_v4.2.2-stable_linux.x86_64.zip
          chmod +x Godot_v4.2.2-stable_linux.x86_64
          sudo mv Godot_v4.2.2-stable_linux.x86_64 /usr/local/bin/godot

      - name: Setup Export Templates
        run: |
          wget -q https://github.com/godotengine/godot/releases/download/4.2.2-stable/Godot_v4.2.2-stable_export_templates.tpz
          mkdir -p ~/.local/share/godot/export_templates/4.2.2.stable
          unzip -q Godot_v4.2.2-stable_export_templates.tpz
          mv templates/* ~/.local/share/godot/export_templates/4.2.2.stable/

      - name: Debug Project
        run: |
          echo "=== Project Structure ==="
          ls -la
          echo ""
          echo "=== Project.godot content ==="
          if [ -f "project.godot" ]; then
            head -20 project.godot
          else
            echo "project.godot not found!"
            find . -name "*.godot" -type f
          fi

      - name: Create Export Presets
        run: |
          cat > export_presets.cfg << 'EOF'
          [preset.0]
          
          name="Android"
          platform="Android"
          runnable=true
          dedicated_server=false
          custom_features=""
          export_filter="all_resources"
          include_filter=""
          exclude_filter=""
          export_path=""
          encryption_include_filters=""
          encryption_exclude_filters=""
          encrypt_pck=false
          encrypt_directory=false
          
          [preset.0.options]
          
          custom_template/debug=""
          custom_template/release=""
          gradle_build/use_gradle_build=false
          gradle_build/export_format=0
          gradle_build/min_sdk=""
          gradle_build/target_sdk=""
          architectures/armeabi-v7a=false
          architectures/arm64-v8a=true
          architectures/x86=false
          architectures/x86_64=false
          version/code=1
          version/name="1.0"
          package/unique_name="com.gamefer.app"
          package/name="GameFer"
          package/signed=false
          permissions/internet=false
          EOF

      - name: Import and Fix Resources
        run: |
          echo "=== Importing project to fix missing resources ==="
          timeout 60 godot --headless --editor --quit || true
          
          echo "=== Checking resource files ==="
          find . -name "*.import" | head -5
          
          echo "=== Testing export presets ==="
          godot --headless --list-export-presets || true

      - name: Export Android APK
        run: |
          mkdir -p build
          echo "=== Starting Android export ==="
          
          # Try export with error handling
          if godot --headless --verbose --export-debug "Android" build/gamefer.apk; then
            echo "✅ Export successful!"
          else
            echo "⚠️  Export had issues, but continuing..."
          fi
          
          echo "=== Checking results ==="
          ls -la build/ || echo "Build directory not found"
          find . -name "*.apk" -exec ls -la {} \; || echo "No APK files found"

      - name: Upload Build Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: android-manual-build
          path: |
            build/
            *.apk
            .godot/
          retention-days: 14
